[project]
name = "python-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask==3.1.1",
    "pre-commit==4.2.0",
]

[dependency-groups]
dev = [
    "ruff==0.11.10",
]
